version: '3'

services:
  pika-fetcher:
    build:
      context: '.'
      dockerfile: Dockerfile-PikaFetcher
    image: 202826568878.dkr.ecr.us-east-2.amazonaws.com/pikabu/pika-fetcher
  pika-web:
    build:
      context: '.'
      dockerfile: Dockerfile-PikaWeb
    image: 202826568878.dkr.ecr.us-east-2.amazonaws.com/pikabu/pika-web