// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PikabusherTmp;

namespace PikabusherTmp.Migrations
{
    [DbContext(typeof(PikabuContext))]
    partial class PikabuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("PikabusherTmp.Comment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTimeUtc");

                    b.Property<long>("ParentId");

                    b.Property<int?>("StoryId");

                    b.Property<string>("UserName");

                    b.HasKey("CommentId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserName");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PikabusherTmp.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTimeUtc");

                    b.Property<DateTime>("LastScanUtc");

                    b.Property<int?>("Rating");

                    b.Property<string>("Title");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("PikabusherTmp.User", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PikabusherTmp.Comment", b =>
                {
                    b.HasOne("PikabusherTmp.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId");

                    b.HasOne("PikabusherTmp.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserName");
                });
#pragma warning restore 612, 618
        }
    }
}
